import { ReactNode } from 'react'
import './globals.css'
import styles from './layout.module.css'
import { Inter } from 'next/font/google'

import Providers from './providers'
import Navbar from '../components/Navbar'

interface Props {
  children: ReactNode
}

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
